/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router

// Import Routes
import { Route as rootRoute } from "./routes/__root";
import { Route as AboutImport } from "./routes/about";
import { Route as ContactImport } from "./routes/contact";
import { Route as IndexImport } from "./routes/index";
import { Route as MenuImport } from "./routes/menu";

// Create/Update Routes
const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as never);

const MenuRoute = MenuImport.update({
  id: "/menu",
  path: "/menu",
  getParentRoute: () => rootRoute,
} as never);

const AboutRoute = AboutImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRoute,
} as never);

const ContactRoute = ContactImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRoute,
} as never);

// Populate the FileRoutesByPath interface
declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/menu": {
      id: "/menu";
      path: "/menu";
      fullPath: "/menu";
      preLoaderRoute: typeof MenuImport;
      parentRoute: typeof rootRoute;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree
export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/menu": typeof MenuRoute;
  "/about": typeof AboutRoute;
  "/contact": typeof ContactRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/menu": typeof MenuRoute;
  "/about": typeof AboutRoute;
  "/contact": typeof ContactRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/menu": typeof MenuRoute;
  "/about": typeof AboutRoute;
  "/contact": typeof ContactRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/menu" | "/about" | "/contact";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/menu" | "/about" | "/contact";
  id: "__root__" | "/" | "/menu" | "/about" | "/contact";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  MenuRoute: typeof MenuRoute;
  AboutRoute: typeof AboutRoute;
  ContactRoute: typeof ContactRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MenuRoute: MenuRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
